# Generated by Django 4.2.5 on 2023-09-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'continents',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.continent')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.country')),
            ],
            options={
                'db_table': 'destinations',
            },
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_date', models.DateTimeField()),
                ('total_seats', models.IntegerField()),
                ('tourist_class_seats', models.IntegerField()),
                ('first_class_seats', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.destination')),
            ],
            options={
                'db_table': 'flies',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=30)),
                ('stars_number', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.destination')),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_days', models.IntegerField()),
                ('remaining_seats', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('departure_fly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure_fly', to='domain.fly')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.destination')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.hotel')),
                ('return_fly', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_fly', to='domain.fly')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField(max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.plan')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('seats_booked', models.IntegerField()),
                ('total_cost', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.client')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.paymentmethod')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.plan')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
